service: text-analyzer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: david-mobapp
  region: eu-north-1
  iam:
    role: arn:aws:iam::626646945997:role/lectures-cloud
  
plugins: 
  - serverless-webpack

package:
  individually: true    

functions:
  wordCount:
    handler: functions/wordCount/index.handler
    events:
      - httpApi:
          path: /word-count
          method: GET
  wordList: 
    handler: functions/wordList/index.handler
    events:
      - httpApi:
          path: /word-list
          method: GET
  summary:
    handler: functions/summary/index.handler
    events:
      - httpApi:
          path: /summary
          method: GET
      

